[project]
name = "labtools"
version = "0.0.1"
license = {file = "LICENSE"}
description = "Python Lab Tools"
readme = "README.md"
dependencies = [
    "numpy",
    "uncertainties",
    "matplotlib",
    "scipy>=1.11",
    "pytest"
]

[tool.pytest.ini_options]
addopts = "--doctest-modules"